workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Sondare
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.sondare.app
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.sondare.app"
        APP_STORE_APPLE_ID: 6754073121
      node: 18
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web app
        script: |
          npm run build
      - name: Install Capacitor
        script: |
          npm install @capacitor/core @capacitor/cli @capacitor/ios
      - name: Add iOS platform and configure deployment target
        script: |
          npx cap add ios || true
          if [ -f ios/App/Podfile ]; then
            echo "platform :ios, '14.0'" > ios/App/Podfile
            echo "use_frameworks!" >> ios/App/Podfile
            echo "" >> ios/App/Podfile
            echo "install! 'cocoapods', :disable_input_output_paths => true" >> ios/App/Podfile
            echo "" >> ios/App/Podfile
            echo "def capacitor_pods" >> ios/App/Podfile
            echo "  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'" >> ios/App/Podfile
            echo "  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'" >> ios/App/Podfile
            echo "end" >> ios/App/Podfile
            echo "" >> ios/App/Podfile
            echo "target 'App' do" >> ios/App/Podfile
            echo "  capacitor_pods" >> ios/App/Podfile
            echo "end" >> ios/App/Podfile
            sed -i '' "s/IPHONEOS_DEPLOYMENT_TARGET = [0-9]*\.[0-9]*/IPHONEOS_DEPLOYMENT_TARGET = 14.0/g" ios/App/App.xcodeproj/project.pbxproj
            cd ios/App && pod install
          fi
      - name: Copy web assets to native project
        script: |
          npx cap copy ios
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Increment build number
        script: |
          cd ios/App
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email: stuart@sondare.me
        recipients:
          - stuart@sondare.me
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - App Store Connect Users
        submit_to_app_store: false

  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.sondare.app"
      node: 18
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web app
        script: |
          npm run build
      - name: Install Capacitor
        script: |
          npm install @capacitor/core @capacitor/cli @capacitor/android
      - name: Add Android platform
        script: |
          npx cap add android
      - name: Update dependencies and copy web assets to native project
        script: |
          npx cap sync android
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build Android release
        script: |
          cd android
          ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/**/*.aab
      - android/app/build/outputs/**/*.apk
    publishing:
      email: stuart@sondare.me
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
