import { Type, Square, Image, CreditCard as Edit, LayoutGrid as Layout, List, CreditCard, Tag, Menu, Navigation, ChevronRight, Star, ShoppingBag, Search, Bell, MessageCircle, Heart, Share2, Settings, User, Camera, Video, Music, Play, Download, Upload, Calendar, Clock, MapPin, Phone, Mail, Lock, Eye, EyeOff, Check, X, Plus, Minus, RefreshCw, Filter, MoreVertical, Layers, Zap, TrendingUp, Award, Shield, Package, Truck, BarChart3, PieChart, Activity, DollarSign, CreditCard as CardIcon, Wifi, Battery, Bluetooth, Volume2, Sun, Moon, Globe, Circle } from 'lucide-react';

export interface ComponentDefinition {
  type: string;
  name: string;
  icon: any;
  defaultProps: Record<string, any>;
  defaultStyles: Record<string, any>;
  defaultWidth: number;
  defaultHeight: number;
}

export const COMPONENT_LIBRARY: ComponentDefinition[] = [
  {
    type: 'text',
    name: 'Text',
    icon: Type,
    defaultProps: {
      text: 'Sample Text',
      fontSize: 16,
      color: '#FFFFFF',
      fontWeight: 'normal',
      fontFamily: 'System',
      textAlign: 'left',
      textDecoration: 'none',
      letterSpacing: 0,
      lineHeight: 1.5,
      textTransform: 'none',
      opacity: 1,
      backgroundColor: 'transparent',
      backgroundImage: null,
      gradientColors: null,
      gradientDirection: 'vertical',
      paddingHorizontal: 0,
      paddingVertical: 0,
      shadowColor: '#000000',
      shadowOpacity: 0,
      shadowRadius: 0,
      shadowOffsetX: 0,
      shadowOffsetY: 2,
      rotation: 0,
      animation: 'none',
      animationDuration: 300,
    },
    defaultStyles: {},
    defaultWidth: 200,
    defaultHeight: 40,
  },
  {
    type: 'button',
    name: 'Button',
    icon: Square,
    defaultProps: {
      text: 'Button',
      backgroundColor: '#FF9500',
      backgroundImage: null,
      textColor: '#FFFFFF',
      fontSize: 16,
      fontFamily: 'System',
      fontWeight: '600',
      borderRadius: 8,
      opacity: 1,
      borderWidth: 0,
      borderColor: '#FF9500',
      paddingHorizontal: 16,
      paddingVertical: 12,
      shadowColor: '#000000',
      shadowOpacity: 0.3,
      shadowRadius: 4,
      shadowOffsetX: 0,
      shadowOffsetY: 2,
      rotation: 0,
      gradientColors: null,
      gradientDirection: 'vertical',
      animation: 'none',
      animationDuration: 300,
      action: 'none',
      navigationTarget: '',
      externalUrl: '',
    },
    defaultStyles: {},
    defaultWidth: 150,
    defaultHeight: 44,
  },
  {
    type: 'input',
    name: 'Input Field',
    icon: Edit,
    defaultProps: {
      placeholder: 'Enter text...',
      backgroundColor: '#1C1C1E',
      backgroundImage: null,
      textColor: '#FFFFFF',
      borderColor: '#3A3A3C',
      borderWidth: 1,
      borderRadius: 8,
      opacity: 1,
      shadowColor: '#000000',
      shadowOpacity: 0,
      shadowRadius: 0,
      shadowOffsetX: 0,
      shadowOffsetY: 0,
    },
    defaultStyles: {},
    defaultWidth: 300,
    defaultHeight: 44,
  },
  {
    type: 'image',
    name: 'Image',
    icon: Image,
    defaultProps: {
      source: 'https://images.pexels.com/photos/1714208/pexels-photo-1714208.jpeg?auto=compress&cs=tinysrgb&w=400',
      borderRadius: 0,
      aspectRatio: '16:9',
      opacity: 1,
      borderWidth: 0,
      borderColor: '#FFFFFF',
      shadowColor: '#000000',
      shadowOpacity: 0,
      shadowRadius: 0,
      shadowOffsetX: 0,
      shadowOffsetY: 0,
      filterBrightness: 100,
      filterContrast: 100,
      filterSaturation: 100,
      filterBlur: 0,
      filterGrayscale: 0,
      filterSepia: 0,
      animation: 'none',
      animationDuration: 300,
    },
    defaultStyles: {},
    defaultWidth: 300,
    defaultHeight: 200,
  },
  {
    type: 'container',
    name: 'Container',
    icon: Layout,
    defaultProps: {
      backgroundColor: '#1C1C1E',
      backgroundImage: null,
      gradientColors: null,
      gradientDirection: 'vertical',
      borderRadius: 12,
      borderColor: '#3A3A3C',
      borderWidth: 1,
      padding: 16,
      opacity: 1,
      shadowColor: '#000000',
      shadowOpacity: 0.2,
      shadowRadius: 8,
      shadowOffsetX: 0,
      shadowOffsetY: 2,
      animation: 'none',
      animationDuration: 300,
    },
    defaultStyles: {},
    defaultWidth: 320,
    defaultHeight: 200,
  },
  {
    type: 'list',
    name: 'List',
    icon: List,
    defaultProps: {
      itemCount: 5,
      itemHeight: 60,
      itemBackgroundColor: '#1C1C1E',
      itemBorderRadius: 8,
      spacing: 8,
      opacity: 1,
      borderWidth: 0,
      borderColor: '#3A3A3C',
      shadowColor: '#000000',
      shadowOpacity: 0,
      shadowRadius: 0,
      shadowOffsetX: 0,
      shadowOffsetY: 0,
    },
    defaultStyles: {},
    defaultWidth: 320,
    defaultHeight: 340,
  },
  {
    type: 'card',
    name: 'Card',
    icon: CreditCard,
    defaultProps: {
      title: 'Card Title',
      subtitle: 'Card subtitle text',
      backgroundColor: '#1C1C1E',
      backgroundImage: null,
      gradientColors: null,
      gradientDirection: 'vertical',
      borderRadius: 12,
      padding: 16,
      opacity: 1,
      borderWidth: 0,
      borderColor: '#3A3A3C',
      shadowColor: '#000000',
      shadowOpacity: 0.2,
      shadowRadius: 8,
      shadowOffsetX: 0,
      shadowOffsetY: 2,
      animation: 'none',
      animationDuration: 300,
    },
    defaultStyles: {},
    defaultWidth: 320,
    defaultHeight: 120,
  },
  {
    type: 'header',
    name: 'Header',
    icon: Tag,
    defaultProps: {
      title: 'Screen Title',
      backgroundColor: '#000000',
      backgroundImage: null,
      textColor: '#FFFFFF',
      fontSize: 20,
      fontWeight: 'bold',
      showBackButton: false,
      opacity: 1,
      borderWidth: 0,
      borderColor: '#3A3A3C',
      shadowColor: '#000000',
      shadowOpacity: 0,
      shadowRadius: 0,
      shadowOffsetX: 0,
      shadowOffsetY: 0,
    },
    defaultStyles: {},
    defaultWidth: 375,
    defaultHeight: 60,
  },
  {
    type: 'icon',
    name: 'Icon',
    icon: Star,
    defaultProps: {
      iconName: 'star',
      color: '#FF9500',
      size: 24,
      opacity: 1,
      rotation: 0,
      backgroundColor: 'transparent',
      padding: 0,
      borderRadius: 0,
    },
    defaultStyles: {},
    defaultWidth: 40,
    defaultHeight: 40,
  },
  {
    type: 'divider',
    name: 'Divider',
    icon: Minus,
    defaultProps: {
      color: '#3A3A3C',
      thickness: 1,
      opacity: 0.5,
      style: 'solid',
    },
    defaultStyles: {},
    defaultWidth: 320,
    defaultHeight: 1,
  },
  {
    type: 'avatar',
    name: 'Avatar',
    icon: User,
    defaultProps: {
      source: 'https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=100',
      size: 60,
      borderRadius: 30,
      borderWidth: 2,
      borderColor: '#FFFFFF',
      opacity: 1,
    },
    defaultStyles: {},
    defaultWidth: 60,
    defaultHeight: 60,
  },
  {
    type: 'badge',
    name: 'Badge',
    icon: Award,
    defaultProps: {
      text: 'New',
      backgroundColor: '#FF3B30',
      textColor: '#FFFFFF',
      fontSize: 12,
      fontWeight: '600',
      borderRadius: 12,
      paddingHorizontal: 8,
      paddingVertical: 4,
    },
    defaultStyles: {},
    defaultWidth: 60,
    defaultHeight: 24,
  },
  {
    type: 'chip',
    name: 'Chip',
    icon: Tag,
    defaultProps: {
      text: 'Category',
      backgroundColor: '#1C1C1E',
      textColor: '#FFFFFF',
      fontSize: 14,
      borderRadius: 16,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderWidth: 1,
      borderColor: '#3A3A3C',
    },
    defaultStyles: {},
    defaultWidth: 100,
    defaultHeight: 32,
  },
  {
    type: 'searchbar',
    name: 'Search Bar',
    icon: Search,
    defaultProps: {
      placeholder: 'Search...',
      backgroundColor: '#1C1C1E',
      textColor: '#FFFFFF',
      iconColor: '#8E8E93',
      borderRadius: 10,
      fontSize: 16,
    },
    defaultStyles: {},
    defaultWidth: 335,
    defaultHeight: 44,
  },
  {
    type: 'switch',
    name: 'Switch',
    icon: Settings,
    defaultProps: {
      isOn: false,
      onColor: '#34C759',
      offColor: '#3A3A3C',
      thumbColor: '#FFFFFF',
    },
    defaultStyles: {},
    defaultWidth: 51,
    defaultHeight: 31,
  },
  {
    type: 'checkbox',
    name: 'Checkbox',
    icon: Check,
    defaultProps: {
      isChecked: false,
      checkedColor: '#FF9500',
      uncheckedColor: '#3A3A3C',
      size: 24,
      borderRadius: 4,
    },
    defaultStyles: {},
    defaultWidth: 24,
    defaultHeight: 24,
  },
  {
    type: 'radio',
    name: 'Radio Button',
    icon: Circle,
    defaultProps: {
      isSelected: false,
      selectedColor: '#FF9500',
      unselectedColor: '#3A3A3C',
      size: 24,
    },
    defaultStyles: {},
    defaultWidth: 24,
    defaultHeight: 24,
  },
  {
    type: 'slider',
    name: 'Slider',
    icon: TrendingUp,
    defaultProps: {
      value: 50,
      minimumValue: 0,
      maximumValue: 100,
      minimumTrackColor: '#FF9500',
      maximumTrackColor: '#3A3A3C',
      thumbColor: '#FFFFFF',
    },
    defaultStyles: {},
    defaultWidth: 300,
    defaultHeight: 40,
  },
  {
    type: 'progressbar',
    name: 'Progress Bar',
    icon: Activity,
    defaultProps: {
      progress: 0.6,
      progressColor: '#34C759',
      backgroundColor: '#1C1C1E',
      height: 8,
      borderRadius: 4,
    },
    defaultStyles: {},
    defaultWidth: 300,
    defaultHeight: 8,
  },
  {
    type: 'spinner',
    name: 'Loading Spinner',
    icon: RefreshCw,
    defaultProps: {
      color: '#FF9500',
      size: 'medium',
    },
    defaultStyles: {},
    defaultWidth: 40,
    defaultHeight: 40,
  },
  {
    type: 'tabbar',
    name: 'Tab Bar',
    icon: Navigation,
    defaultProps: {
      tabs: ['Home', 'Search', 'Profile'],
      activeTab: 0,
      backgroundColor: '#1C1C1E',
      activeColor: '#FF9500',
      inactiveColor: '#8E8E93',
      height: 60,
    },
    defaultStyles: {},
    defaultWidth: 375,
    defaultHeight: 60,
  },
  {
    type: 'navbar',
    name: 'Navigation Bar',
    icon: Menu,
    defaultProps: {
      items: ['Home', 'Products', 'Cart', 'Profile'],
      backgroundColor: '#000000',
      textColor: '#FFFFFF',
      activeColor: '#FF9500',
      fontSize: 16,
    },
    defaultStyles: {},
    defaultWidth: 375,
    defaultHeight: 50,
  },
  {
    type: 'bottomsheet',
    name: 'Bottom Sheet',
    icon: Layers,
    defaultProps: {
      title: 'Options',
      backgroundColor: '#1C1C1E',
      textColor: '#FFFFFF',
      borderRadius: 20,
      height: 300,
    },
    defaultStyles: {},
    defaultWidth: 375,
    defaultHeight: 300,
  },
  {
    type: 'modal',
    name: 'Modal',
    icon: Layout,
    defaultProps: {
      title: 'Modal Title',
      backgroundColor: '#1C1C1E',
      textColor: '#FFFFFF',
      borderRadius: 12,
      padding: 20,
    },
    defaultStyles: {},
    defaultWidth: 335,
    defaultHeight: 250,
  },
  {
    type: 'toast',
    name: 'Toast Notification',
    icon: Bell,
    defaultProps: {
      message: 'Action completed',
      type: 'success',
      backgroundColor: '#34C759',
      textColor: '#FFFFFF',
      borderRadius: 8,
    },
    defaultStyles: {},
    defaultWidth: 335,
    defaultHeight: 50,
  },
  {
    type: 'alert',
    name: 'Alert Dialog',
    icon: Bell,
    defaultProps: {
      title: 'Alert',
      message: 'Are you sure?',
      confirmText: 'Yes',
      cancelText: 'No',
      backgroundColor: '#1C1C1E',
      textColor: '#FFFFFF',
    },
    defaultStyles: {},
    defaultWidth: 300,
    defaultHeight: 180,
  },
  {
    type: 'accordion',
    name: 'Accordion',
    icon: ChevronRight,
    defaultProps: {
      title: 'Expand Section',
      isExpanded: false,
      backgroundColor: '#1C1C1E',
      textColor: '#FFFFFF',
      borderRadius: 8,
    },
    defaultStyles: {},
    defaultWidth: 335,
    defaultHeight: 60,
  },
  {
    type: 'datepicker',
    name: 'Date Picker',
    icon: Calendar,
    defaultProps: {
      selectedDate: new Date().toISOString(),
      textColor: '#FFFFFF',
      accentColor: '#FF9500',
      mode: 'date',
    },
    defaultStyles: {},
    defaultWidth: 335,
    defaultHeight: 200,
  },
  {
    type: 'timepicker',
    name: 'Time Picker',
    icon: Clock,
    defaultProps: {
      selectedTime: '12:00',
      textColor: '#FFFFFF',
      accentColor: '#FF9500',
    },
    defaultStyles: {},
    defaultWidth: 200,
    defaultHeight: 150,
  },
  {
    type: 'dropdown',
    name: 'Dropdown',
    icon: ChevronRight,
    defaultProps: {
      placeholder: 'Select option',
      options: ['Option 1', 'Option 2', 'Option 3'],
      backgroundColor: '#1C1C1E',
      textColor: '#FFFFFF',
      borderRadius: 8,
    },
    defaultStyles: {},
    defaultWidth: 300,
    defaultHeight: 44,
  },
  {
    type: 'rating',
    name: 'Rating',
    icon: Star,
    defaultProps: {
      rating: 4,
      maxRating: 5,
      starColor: '#FFD700',
      emptyStarColor: '#3A3A3C',
      size: 24,
    },
    defaultStyles: {},
    defaultWidth: 140,
    defaultHeight: 30,
  },
  {
    type: 'stepper',
    name: 'Stepper',
    icon: TrendingUp,
    defaultProps: {
      currentStep: 2,
      totalSteps: 4,
      activeColor: '#FF9500',
      inactiveColor: '#3A3A3C',
    },
    defaultStyles: {},
    defaultWidth: 300,
    defaultHeight: 40,
  },
  {
    type: 'carousel',
    name: 'Carousel',
    icon: Image,
    defaultProps: {
      images: [
        'https://images.pexels.com/photos/1714208/pexels-photo-1714208.jpeg?auto=compress&cs=tinysrgb&w=400',
        'https://images.pexels.com/photos/1103970/pexels-photo-1103970.jpeg?auto=compress&cs=tinysrgb&w=400'
      ],
      autoPlay: true,
      interval: 3000,
      showDots: true,
      borderRadius: 12,
    },
    defaultStyles: {},
    defaultWidth: 335,
    defaultHeight: 200,
  },
  {
    type: 'video',
    name: 'Video Player',
    icon: Video,
    defaultProps: {
      source: 'https://example.com/video.mp4',
      poster: 'https://images.pexels.com/photos/1714208/pexels-photo-1714208.jpeg?auto=compress&cs=tinysrgb&w=400',
      autoPlay: false,
      loop: false,
      controls: true,
      borderRadius: 12,
    },
    defaultStyles: {},
    defaultWidth: 335,
    defaultHeight: 200,
  },
  {
    type: 'audio',
    name: 'Audio Player',
    icon: Music,
    defaultProps: {
      source: 'https://example.com/audio.mp3',
      title: 'Song Title',
      artist: 'Artist Name',
      backgroundColor: '#1C1C1E',
      accentColor: '#FF9500',
    },
    defaultStyles: {},
    defaultWidth: 335,
    defaultHeight: 80,
  },
  {
    type: 'map',
    name: 'Map View',
    icon: MapPin,
    defaultProps: {
      latitude: 37.7749,
      longitude: -122.4194,
      zoom: 12,
      markers: [],
      borderRadius: 12,
    },
    defaultStyles: {},
    defaultWidth: 335,
    defaultHeight: 250,
  },
  {
    type: 'webview',
    name: 'Web View',
    icon: Globe,
    defaultProps: {
      url: 'https://example.com',
      backgroundColor: '#FFFFFF',
    },
    defaultStyles: {},
    defaultWidth: 335,
    defaultHeight: 400,
  },
  {
    type: 'skeleton',
    name: 'Skeleton Loader',
    icon: RefreshCw,
    defaultProps: {
      width: 200,
      height: 20,
      borderRadius: 4,
      backgroundColor: '#1C1C1E',
      highlightColor: '#2C2C2E',
    },
    defaultStyles: {},
    defaultWidth: 200,
    defaultHeight: 20,
  },
  {
    type: 'chart',
    name: 'Chart',
    icon: BarChart3,
    defaultProps: {
      type: 'bar',
      data: [30, 50, 70, 45, 60],
      labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      color: '#FF9500',
      backgroundColor: '#1C1C1E',
    },
    defaultStyles: {},
    defaultWidth: 335,
    defaultHeight: 200,
  },
  {
    type: 'qrcode',
    name: 'QR Code',
    icon: Square,
    defaultProps: {
      value: 'https://example.com',
      size: 150,
      backgroundColor: '#FFFFFF',
      foregroundColor: '#000000',
    },
    defaultStyles: {},
    defaultWidth: 150,
    defaultHeight: 150,
  },
  {
    type: 'floatingbutton',
    name: 'Floating Action Button',
    icon: Plus,
    defaultProps: {
      icon: 'plus',
      backgroundColor: '#FF9500',
      iconColor: '#FFFFFF',
      size: 56,
      position: 'bottom-right',
    },
    defaultStyles: {},
    defaultWidth: 56,
    defaultHeight: 56,
  },
];

interface ComponentLibraryProps {
  onSelectComponent: (component: ComponentDefinition) => void;
}

export function ComponentLibrary({ onSelectComponent }: ComponentLibraryProps) {
  return (
    <div className="h-full flex flex-col">
      <div className="p-4 border-b border-white/10">
        <h3 className="font-semibold">Components</h3>
        <p className="text-xs text-white/60">Drag to canvas</p>
      </div>

      <div className="flex-1 overflow-y-auto p-3 space-y-2 scrollbar-hide">
        {COMPONENT_LIBRARY.map((component) => {
          const Icon = component.icon;
          return (
            <button
              key={component.type}
              onClick={() => onSelectComponent(component)}
              className="w-full glass-card p-3 flex items-center gap-3 hover:bg-white/10 transition-colors active:scale-95 text-left"
            >
              <div className="bg-orange-500/20 p-2 rounded-lg flex-shrink-0">
                <Icon className="w-4 h-4 text-orange-500" />
              </div>
              <div className="flex-1 min-w-0">
                <p className="font-medium text-sm">{component.name}</p>
                <p className="text-xs text-white/60 truncate">{component.type}</p>
              </div>
            </button>
          );
        })}
      </div>
    </div>
  );
}
