import { useState } from 'react';
import { X, Sparkles, ShoppingBag, Heart, TrendingUp, Utensils, Plane, GraduationCap, Home, Building } from 'lucide-react';

interface Template {
  id: string;
  name: string;
  description: string;
  category: string;
  icon: any;
  components: any[];
}

const TEMPLATES: Template[] = [
  {
    id: 'ecommerce-product-grid',
    name: 'E-Commerce Product Grid',
    description: 'Modern product listing with cards',
    category: 'E-Commerce',
    icon: ShoppingBag,
    components: [
      {
        type: 'header',
        props: {
          title: 'Shop',
          backgroundColor: '#FFFFFF',
          textColor: '#000000',
          fontSize: 24,
          fontWeight: 'bold',
          showBackButton: false,
          opacity: 1,
          borderWidth: 0,
          shadowColor: '#000000',
          shadowOpacity: 0.1,
          shadowRadius: 4,
          shadowOffsetX: 0,
          shadowOffsetY: 2,
        },
        position_x: 0,
        position_y: 0,
        width: 375,
        height: 60,
      },
      {
        type: 'input',
        props: {
          placeholder: 'Search products...',
          backgroundColor: '#F5F5F5',
          textColor: '#000000',
          borderColor: '#E0E0E0',
          borderWidth: 1,
          borderRadius: 24,
          opacity: 1,
        },
        position_x: 20,
        position_y: 80,
        width: 335,
        height: 48,
      },
      {
        type: 'card',
        props: {
          title: 'Premium Headphones',
          subtitle: '$299.99',
          backgroundColor: '#FFFFFF',
          borderRadius: 16,
          padding: 12,
          opacity: 1,
          borderWidth: 1,
          borderColor: '#E0E0E0',
          shadowColor: '#000000',
          shadowOpacity: 0.08,
          shadowRadius: 12,
          shadowOffsetX: 0,
          shadowOffsetY: 4,
        },
        position_x: 20,
        position_y: 150,
        width: 165,
        height: 220,
      },
      {
        type: 'card',
        props: {
          title: 'Smart Watch',
          subtitle: '$199.99',
          backgroundColor: '#FFFFFF',
          borderRadius: 16,
          padding: 12,
          opacity: 1,
          borderWidth: 1,
          borderColor: '#E0E0E0',
          shadowColor: '#000000',
          shadowOpacity: 0.08,
          shadowRadius: 12,
          shadowOffsetX: 0,
          shadowOffsetY: 4,
        },
        position_x: 190,
        position_y: 150,
        width: 165,
        height: 220,
      },
    ],
  },
  {
    id: 'social-profile',
    name: 'Social Profile',
    description: 'Modern social media profile',
    category: 'Social',
    icon: Heart,
    components: [
      {
        type: 'header',
        props: {
          title: 'Profile',
          backgroundColor: '#000000',
          textColor: '#FFFFFF',
          fontSize: 20,
          fontWeight: 'bold',
          showBackButton: true,
          opacity: 1,
        },
        position_x: 0,
        position_y: 0,
        width: 375,
        height: 60,
      },
      {
        type: 'image',
        props: {
          source: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=400',
          borderRadius: 60,
          aspectRatio: '1:1',
          opacity: 1,
          borderWidth: 3,
          borderColor: '#FF9500',
          shadowColor: '#FF9500',
          shadowOpacity: 0.3,
          shadowRadius: 16,
          shadowOffsetX: 0,
          shadowOffsetY: 0,
        },
        position_x: 137,
        position_y: 80,
        width: 120,
        height: 120,
      },
      {
        type: 'text',
        props: {
          text: 'John Doe',
          fontSize: 24,
          color: '#FFFFFF',
          fontWeight: 'bold',
          fontFamily: 'System',
          textAlign: 'center',
          opacity: 1,
        },
        position_x: 87,
        position_y: 220,
        width: 200,
        height: 32,
      },
      {
        type: 'text',
        props: {
          text: '@johndoe',
          fontSize: 16,
          color: '#FFFFFF99',
          fontWeight: 'normal',
          fontFamily: 'System',
          textAlign: 'center',
          opacity: 1,
        },
        position_x: 137,
        position_y: 260,
        width: 100,
        height: 24,
      },
      {
        type: 'container',
        props: {
          backgroundColor: '#1C1C1E',
          borderRadius: 16,
          borderColor: '#3A3A3C',
          borderWidth: 1,
          padding: 20,
          opacity: 1,
        },
        position_x: 20,
        position_y: 310,
        width: 335,
        height: 100,
      },
    ],
  },
  {
    id: 'fitness-workout',
    name: 'Fitness Workout Tracker',
    description: 'Exercise tracking interface',
    category: 'Fitness',
    icon: TrendingUp,
    components: [
      {
        type: 'header',
        props: {
          title: 'Today\'s Workout',
          backgroundColor: '#10B981',
          textColor: '#FFFFFF',
          fontSize: 22,
          fontWeight: 'bold',
          showBackButton: false,
          opacity: 1,
        },
        position_x: 0,
        position_y: 0,
        width: 375,
        height: 60,
      },
      {
        type: 'card',
        props: {
          title: '1,234',
          subtitle: 'Steps Today',
          backgroundColor: '#FFFFFF',
          borderRadius: 20,
          padding: 20,
          opacity: 1,
          shadowColor: '#10B981',
          shadowOpacity: 0.2,
          shadowRadius: 16,
          shadowOffsetX: 0,
          shadowOffsetY: 4,
        },
        position_x: 20,
        position_y: 80,
        width: 165,
        height: 120,
      },
      {
        type: 'card',
        props: {
          title: '432',
          subtitle: 'Calories',
          backgroundColor: '#FFFFFF',
          borderRadius: 20,
          padding: 20,
          opacity: 1,
          shadowColor: '#EF4444',
          shadowOpacity: 0.2,
          shadowRadius: 16,
          shadowOffsetX: 0,
          shadowOffsetY: 4,
        },
        position_x: 190,
        position_y: 80,
        width: 165,
        height: 120,
      },
      {
        type: 'list',
        props: {
          itemCount: 4,
          itemHeight: 70,
          itemBackgroundColor: '#FFFFFF',
          itemBorderRadius: 12,
          spacing: 12,
          opacity: 1,
          shadowColor: '#000000',
          shadowOpacity: 0.05,
          shadowRadius: 8,
        },
        position_x: 20,
        position_y: 220,
        width: 335,
        height: 320,
      },
    ],
  },
  {
    id: 'finance-dashboard',
    name: 'Finance Dashboard',
    description: 'Financial overview and stats',
    category: 'Finance',
    icon: TrendingUp,
    components: [
      {
        type: 'header',
        props: {
          title: 'Dashboard',
          backgroundColor: '#1E40AF',
          textColor: '#FFFFFF',
          fontSize: 22,
          fontWeight: 'bold',
          showBackButton: false,
          opacity: 1,
        },
        position_x: 0,
        position_y: 0,
        width: 375,
        height: 60,
      },
      {
        type: 'container',
        props: {
          backgroundColor: '#1E40AF',
          borderRadius: 20,
          padding: 24,
          opacity: 1,
          shadowColor: '#1E40AF',
          shadowOpacity: 0.4,
          shadowRadius: 20,
          shadowOffsetX: 0,
          shadowOffsetY: 8,
        },
        position_x: 20,
        position_y: 80,
        width: 335,
        height: 140,
      },
      {
        type: 'text',
        props: {
          text: 'Total Balance',
          fontSize: 14,
          color: '#FFFFFFAA',
          fontWeight: '500',
          textAlign: 'left',
        },
        position_x: 44,
        position_y: 108,
        width: 150,
        height: 20,
      },
      {
        type: 'text',
        props: {
          text: '$24,532.00',
          fontSize: 32,
          color: '#FFFFFF',
          fontWeight: 'bold',
          fontFamily: 'System',
          textAlign: 'left',
        },
        position_x: 44,
        position_y: 135,
        width: 280,
        height: 44,
      },
      {
        type: 'card',
        props: {
          title: 'Income',
          subtitle: '+$3,240',
          backgroundColor: '#10B981',
          borderRadius: 16,
          padding: 16,
          opacity: 1,
        },
        position_x: 20,
        position_y: 240,
        width: 165,
        height: 100,
      },
      {
        type: 'card',
        props: {
          title: 'Expenses',
          subtitle: '-$1,832',
          backgroundColor: '#EF4444',
          borderRadius: 16,
          padding: 16,
          opacity: 1,
        },
        position_x: 190,
        position_y: 240,
        width: 165,
        height: 100,
      },
    ],
  },
  {
    id: 'food-restaurant-list',
    name: 'Restaurant List',
    description: 'Food delivery restaurant browse',
    category: 'Food',
    icon: Utensils,
    components: [
      {
        type: 'header',
        props: {
          title: 'Restaurants',
          backgroundColor: '#FFFFFF',
          textColor: '#000000',
          fontSize: 24,
          fontWeight: 'bold',
          showBackButton: false,
          opacity: 1,
          shadowColor: '#000000',
          shadowOpacity: 0.08,
          shadowRadius: 4,
          shadowOffsetX: 0,
          shadowOffsetY: 2,
        },
        position_x: 0,
        position_y: 0,
        width: 375,
        height: 60,
      },
      {
        type: 'input',
        props: {
          placeholder: 'Search cuisine, restaurant...',
          backgroundColor: '#F9FAFB',
          textColor: '#000000',
          borderColor: '#E5E7EB',
          borderWidth: 1,
          borderRadius: 12,
        },
        position_x: 20,
        position_y: 80,
        width: 335,
        height: 48,
      },
      {
        type: 'container',
        props: {
          backgroundColor: '#FFFFFF',
          borderRadius: 16,
          padding: 12,
          borderWidth: 1,
          borderColor: '#E5E7EB',
          shadowColor: '#000000',
          shadowOpacity: 0.05,
          shadowRadius: 12,
          shadowOffsetX: 0,
          shadowOffsetY: 4,
        },
        position_x: 20,
        position_y: 150,
        width: 335,
        height: 140,
      },
      {
        type: 'image',
        props: {
          source: 'https://images.pexels.com/photos/262978/pexels-photo-262978.jpeg?auto=compress&cs=tinysrgb&w=400',
          borderRadius: 12,
          aspectRatio: '16:9',
          opacity: 1,
        },
        position_x: 32,
        position_y: 162,
        width: 120,
        height: 90,
      },
      {
        type: 'text',
        props: {
          text: 'Italian Bistro',
          fontSize: 18,
          color: '#000000',
          fontWeight: 'bold',
        },
        position_x: 165,
        position_y: 165,
        width: 170,
        height: 28,
      },
      {
        type: 'text',
        props: {
          text: 'Italian • 25-30 min',
          fontSize: 14,
          color: '#6B7280',
          fontWeight: 'normal',
        },
        position_x: 165,
        position_y: 198,
        width: 170,
        height: 20,
      },
    ],
  },
  {
    id: 'travel-destination',
    name: 'Travel Destinations',
    description: 'Browse and explore travel destinations',
    category: 'Travel',
    icon: Plane,
    components: [
      {
        type: 'header',
        props: {
          title: 'Explore',
          backgroundColor: '#0EA5E9',
          textColor: '#FFFFFF',
          fontSize: 24,
          fontWeight: 'bold',
          showBackButton: false,
        },
        position_x: 0,
        position_y: 0,
        width: 375,
        height: 60,
      },
      {
        type: 'image',
        props: {
          source: 'https://images.pexels.com/photos/1285625/pexels-photo-1285625.jpeg?auto=compress&cs=tinysrgb&w=600',
          borderRadius: 20,
          aspectRatio: '16:9',
          opacity: 1,
          shadowColor: '#000000',
          shadowOpacity: 0.3,
          shadowRadius: 20,
          shadowOffsetX: 0,
          shadowOffsetY: 10,
        },
        position_x: 20,
        position_y: 80,
        width: 335,
        height: 200,
      },
      {
        type: 'text',
        props: {
          text: 'Paris, France',
          fontSize: 28,
          color: '#FFFFFF',
          fontWeight: 'bold',
          fontFamily: 'System',
          textAlign: 'left',
          shadowColor: '#000000',
          shadowOpacity: 0.5,
          shadowRadius: 8,
          shadowOffsetX: 0,
          shadowOffsetY: 2,
        },
        position_x: 40,
        position_y: 220,
        width: 295,
        height: 36,
      },
      {
        type: 'button',
        props: {
          text: 'View Details',
          backgroundColor: '#FFFFFF',
          textColor: '#0EA5E9',
          fontSize: 16,
          fontWeight: '600',
          borderRadius: 12,
          opacity: 1,
          shadowColor: '#000000',
          shadowOpacity: 0.1,
          shadowRadius: 8,
        },
        position_x: 20,
        position_y: 300,
        width: 335,
        height: 50,
      },
    ],
  },
  {
    id: 'education-course-list',
    name: 'Course Library',
    description: 'Educational course listing',
    category: 'Education',
    icon: GraduationCap,
    components: [
      {
        type: 'header',
        props: {
          title: 'My Courses',
          backgroundColor: '#7C3AED',
          textColor: '#FFFFFF',
          fontSize: 22,
          fontWeight: 'bold',
          showBackButton: false,
        },
        position_x: 0,
        position_y: 0,
        width: 375,
        height: 60,
      },
      {
        type: 'card',
        props: {
          title: 'React Native Mastery',
          subtitle: '12 lessons • 45% complete',
          backgroundColor: '#FFFFFF',
          borderRadius: 16,
          padding: 16,
          borderWidth: 1,
          borderColor: '#E5E7EB',
          shadowColor: '#7C3AED',
          shadowOpacity: 0.15,
          shadowRadius: 12,
          shadowOffsetX: 0,
          shadowOffsetY: 4,
        },
        position_x: 20,
        position_y: 80,
        width: 335,
        height: 120,
      },
      {
        type: 'card',
        props: {
          title: 'UI/UX Design Fundamentals',
          subtitle: '8 lessons • 20% complete',
          backgroundColor: '#FFFFFF',
          borderRadius: 16,
          padding: 16,
          borderWidth: 1,
          borderColor: '#E5E7EB',
          shadowColor: '#7C3AED',
          shadowOpacity: 0.15,
          shadowRadius: 12,
          shadowOffsetX: 0,
          shadowOffsetY: 4,
        },
        position_x: 20,
        position_y: 220,
        width: 335,
        height: 120,
      },
    ],
  },
  {
    id: 'realestate-property',
    name: 'Property Listing',
    description: 'Real estate property browse',
    category: 'Real Estate',
    icon: Building,
    components: [
      {
        type: 'header',
        props: {
          title: 'Properties',
          backgroundColor: '#FFFFFF',
          textColor: '#000000',
          fontSize: 24,
          fontWeight: 'bold',
          showBackButton: false,
          shadowColor: '#000000',
          shadowOpacity: 0.08,
          shadowRadius: 4,
        },
        position_x: 0,
        position_y: 0,
        width: 375,
        height: 60,
      },
      {
        type: 'image',
        props: {
          source: 'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=600',
          borderRadius: 16,
          aspectRatio: '16:9',
          opacity: 1,
        },
        position_x: 20,
        position_y: 80,
        width: 335,
        height: 200,
      },
      {
        type: 'text',
        props: {
          text: '$1,250,000',
          fontSize: 28,
          color: '#10B981',
          fontWeight: 'bold',
          fontFamily: 'System',
        },
        position_x: 20,
        position_y: 300,
        width: 200,
        height: 36,
      },
      {
        type: 'text',
        props: {
          text: 'Modern Villa',
          fontSize: 20,
          color: '#000000',
          fontWeight: 'bold',
        },
        position_x: 20,
        position_y: 345,
        width: 335,
        height: 28,
      },
      {
        type: 'text',
        props: {
          text: '4 beds • 3 baths • 2,400 sqft',
          fontSize: 14,
          color: '#6B7280',
          fontWeight: 'normal',
        },
        position_x: 20,
        position_y: 380,
        width: 335,
        height: 20,
      },
    ],
  },
  {
    id: 'dark-modern-login',
    name: 'Dark Modern Login',
    description: 'Sleek dark theme authentication',
    category: 'Auth',
    icon: Sparkles,
    components: [
      {
        type: 'text',
        props: {
          text: 'Welcome Back',
          fontSize: 32,
          color: '#FFFFFF',
          fontWeight: 'bold',
          fontFamily: 'System',
          textAlign: 'center',
          letterSpacing: -0.5,
        },
        position_x: 87,
        position_y: 100,
        width: 200,
        height: 44,
      },
      {
        type: 'text',
        props: {
          text: 'Sign in to continue your journey',
          fontSize: 14,
          color: '#FFFFFF99',
          fontWeight: 'normal',
          textAlign: 'center',
        },
        position_x: 87,
        position_y: 155,
        width: 200,
        height: 20,
      },
      {
        type: 'input',
        props: {
          placeholder: 'Email',
          backgroundColor: '#FFFFFF15',
          textColor: '#FFFFFF',
          borderColor: '#FFFFFF30',
          borderWidth: 1,
          borderRadius: 16,
        },
        position_x: 37,
        position_y: 210,
        width: 300,
        height: 56,
      },
      {
        type: 'input',
        props: {
          placeholder: 'Password',
          backgroundColor: '#FFFFFF15',
          textColor: '#FFFFFF',
          borderColor: '#FFFFFF30',
          borderWidth: 1,
          borderRadius: 16,
        },
        position_x: 37,
        position_y: 286,
        width: 300,
        height: 56,
      },
      {
        type: 'button',
        props: {
          text: 'Sign In',
          backgroundColor: '#FF9500',
          textColor: '#FFFFFF',
          fontSize: 16,
          fontWeight: 'bold',
          borderRadius: 16,
          shadowColor: '#FF9500',
          shadowOpacity: 0.4,
          shadowRadius: 16,
          shadowOffsetX: 0,
          shadowOffsetY: 8,
        },
        position_x: 37,
        position_y: 372,
        width: 300,
        height: 56,
      },
    ],
  },
  {
    id: 'minimalist-dashboard',
    name: 'Minimalist Dashboard',
    description: 'Clean white space design',
    category: 'Dashboard',
    icon: Home,
    components: [
      {
        type: 'text',
        props: {
          text: 'Dashboard',
          fontSize: 36,
          color: '#000000',
          fontWeight: 'bold',
          fontFamily: 'System',
          textAlign: 'left',
          letterSpacing: -1,
        },
        position_x: 20,
        position_y: 60,
        width: 335,
        height: 48,
      },
      {
        type: 'text',
        props: {
          text: 'Welcome back, here is your overview',
          fontSize: 14,
          color: '#6B7280',
          fontWeight: 'normal',
          textAlign: 'left',
        },
        position_x: 20,
        position_y: 118,
        width: 335,
        height: 20,
      },
      {
        type: 'container',
        props: {
          backgroundColor: '#F9FAFB',
          borderRadius: 20,
          padding: 24,
          borderWidth: 0,
        },
        position_x: 20,
        position_y: 160,
        width: 335,
        height: 140,
      },
      {
        type: 'container',
        props: {
          backgroundColor: '#F9FAFB',
          borderRadius: 20,
          padding: 24,
          borderWidth: 0,
        },
        position_x: 20,
        position_y: 320,
        width: 335,
        height: 140,
      },
    ],
  },
  {
    id: 'ecommerce-checkout',
    name: 'Checkout Flow',
    description: 'Complete checkout with payment',
    category: 'E-Commerce',
    icon: ShoppingBag,
    components: [
      {
        type: 'header',
        props: {
          title: 'Checkout',
          backgroundColor: '#FFFFFF',
          textColor: '#000000',
          fontSize: 22,
          fontWeight: 'bold',
          showBackButton: true,
        },
        position_x: 0,
        position_y: 0,
        width: 375,
        height: 60,
      },
      {
        type: 'text',
        props: {
          text: 'Order Summary',
          fontSize: 20,
          color: '#000000',
          fontWeight: 'bold',
        },
        position_x: 20,
        position_y: 80,
        width: 335,
        height: 28,
      },
      {
        type: 'card',
        props: {
          title: 'Subtotal',
          subtitle: '$124.99',
          backgroundColor: '#F9FAFB',
          borderRadius: 12,
          padding: 16,
          borderWidth: 0,
        },
        position_x: 20,
        position_y: 120,
        width: 335,
        height: 80,
      },
      {
        type: 'button',
        props: {
          text: 'Continue to Payment',
          backgroundColor: '#10B981',
          textColor: '#FFFFFF',
          fontSize: 16,
          fontWeight: 'bold',
          borderRadius: 12,
          gradientColors: ['#10B981', '#059669'],
          gradientDirection: 'horizontal',
          shadowColor: '#10B981',
          shadowOpacity: 0.4,
          shadowRadius: 12,
        },
        position_x: 20,
        position_y: 500,
        width: 335,
        height: 56,
      },
    ],
  },
  {
    id: 'fitness-exercise-detail',
    name: 'Exercise Detail',
    description: 'Workout exercise with timer',
    category: 'Fitness',
    icon: TrendingUp,
    components: [
      {
        type: 'image',
        props: {
          source: 'https://images.pexels.com/photos/416778/pexels-photo-416778.jpeg?auto=compress&cs=tinysrgb&w=600',
          borderRadius: 0,
          aspectRatio: '16:9',
          opacity: 1,
        },
        position_x: 0,
        position_y: 0,
        width: 375,
        height: 250,
      },
      {
        type: 'text',
        props: {
          text: 'Push Ups',
          fontSize: 28,
          color: '#000000',
          fontWeight: 'bold',
        },
        position_x: 20,
        position_y: 270,
        width: 335,
        height: 36,
      },
      {
        type: 'container',
        props: {
          backgroundColor: '#EF4444',
          borderRadius: 16,
          padding: 20,
          gradientColors: ['#EF4444', '#DC2626'],
          gradientDirection: 'diagonal',
        },
        position_x: 20,
        position_y: 330,
        width: 335,
        height: 100,
      },
      {
        type: 'text',
        props: {
          text: '3 Sets × 15 Reps',
          fontSize: 16,
          color: '#6B7280',
          fontWeight: '500',
        },
        position_x: 20,
        position_y: 450,
        width: 335,
        height: 24,
      },
    ],
  },
  {
    id: 'food-menu-detail',
    name: 'Food Menu',
    description: 'Restaurant menu with items',
    category: 'Food',
    icon: Utensils,
    components: [
      {
        type: 'header',
        props: {
          title: 'Menu',
          backgroundColor: '#FFFFFF',
          textColor: '#000000',
          fontSize: 24,
          fontWeight: 'bold',
          showBackButton: true,
        },
        position_x: 0,
        position_y: 0,
        width: 375,
        height: 60,
      },
      {
        type: 'container',
        props: {
          backgroundColor: '#FFFFFF',
          borderRadius: 16,
          padding: 12,
          borderWidth: 1,
          borderColor: '#E5E7EB',
        },
        position_x: 20,
        position_y: 80,
        width: 335,
        height: 120,
      },
      {
        type: 'text',
        props: {
          text: 'Margherita Pizza',
          fontSize: 18,
          color: '#000000',
          fontWeight: 'bold',
        },
        position_x: 40,
        position_y: 95,
        width: 200,
        height: 26,
      },
      {
        type: 'text',
        props: {
          text: '$12.99',
          fontSize: 20,
          color: '#EF4444',
          fontWeight: 'bold',
        },
        position_x: 260,
        position_y: 95,
        width: 75,
        height: 26,
      },
      {
        type: 'button',
        props: {
          text: 'Add to Cart',
          backgroundColor: '#10B981',
          textColor: '#FFFFFF',
          fontSize: 14,
          fontWeight: '600',
          borderRadius: 8,
        },
        position_x: 220,
        position_y: 155,
        width: 115,
        height: 36,
      },
    ],
  },
  {
    id: 'travel-booking',
    name: 'Flight Booking',
    description: 'Travel booking interface',
    category: 'Travel',
    icon: Plane,
    components: [
      {
        type: 'header',
        props: {
          title: 'Book Flight',
          backgroundColor: '#0EA5E9',
          textColor: '#FFFFFF',
          fontSize: 22,
          fontWeight: 'bold',
          showBackButton: true,
        },
        position_x: 0,
        position_y: 0,
        width: 375,
        height: 60,
      },
      {
        type: 'container',
        props: {
          backgroundColor: '#FFFFFF',
          borderRadius: 16,
          padding: 20,
          borderWidth: 1,
          borderColor: '#E5E7EB',
          shadowColor: '#000000',
          shadowOpacity: 0.1,
          shadowRadius: 12,
        },
        position_x: 20,
        position_y: 80,
        width: 335,
        height: 200,
      },
      {
        type: 'input',
        props: {
          placeholder: 'From',
          backgroundColor: '#F9FAFB',
          textColor: '#000000',
          borderColor: '#E5E7EB',
          borderWidth: 1,
          borderRadius: 8,
        },
        position_x: 40,
        position_y: 110,
        width: 295,
        height: 44,
      },
      {
        type: 'input',
        props: {
          placeholder: 'To',
          backgroundColor: '#F9FAFB',
          textColor: '#000000',
          borderColor: '#E5E7EB',
          borderWidth: 1,
          borderRadius: 8,
        },
        position_x: 40,
        position_y: 170,
        width: 295,
        height: 44,
      },
      {
        type: 'button',
        props: {
          text: 'Search Flights',
          backgroundColor: '#0EA5E9',
          textColor: '#FFFFFF',
          fontSize: 16,
          fontWeight: 'bold',
          borderRadius: 12,
          gradientColors: ['#0EA5E9', '#0284C7'],
        },
        position_x: 20,
        position_y: 300,
        width: 335,
        height: 52,
      },
    ],
  },
  {
    id: 'medical-appointment',
    name: 'Doctor Appointment',
    description: 'Medical appointment booking',
    category: 'Medical',
    icon: Heart,
    components: [
      {
        type: 'header',
        props: {
          title: 'Book Appointment',
          backgroundColor: '#06B6D4',
          textColor: '#FFFFFF',
          fontSize: 22,
          fontWeight: 'bold',
          showBackButton: true,
        },
        position_x: 0,
        position_y: 0,
        width: 375,
        height: 60,
      },
      {
        type: 'card',
        props: {
          title: 'Dr. Sarah Johnson',
          subtitle: 'Cardiologist',
          backgroundColor: '#FFFFFF',
          borderRadius: 16,
          padding: 16,
          borderWidth: 1,
          borderColor: '#E5E7EB',
        },
        position_x: 20,
        position_y: 80,
        width: 335,
        height: 100,
      },
      {
        type: 'text',
        props: {
          text: 'Select Date & Time',
          fontSize: 18,
          color: '#000000',
          fontWeight: 'bold',
        },
        position_x: 20,
        position_y: 200,
        width: 335,
        height: 28,
      },
      {
        type: 'container',
        props: {
          backgroundColor: '#F0F9FF',
          borderRadius: 12,
          padding: 16,
          borderWidth: 1,
          borderColor: '#BAE6FD',
        },
        position_x: 20,
        position_y: 240,
        width: 335,
        height: 80,
      },
      {
        type: 'button',
        props: {
          text: 'Confirm Appointment',
          backgroundColor: '#06B6D4',
          textColor: '#FFFFFF',
          fontSize: 16,
          fontWeight: 'bold',
          borderRadius: 12,
        },
        position_x: 20,
        position_y: 500,
        width: 335,
        height: 52,
      },
    ],
  },
  {
    id: 'news-article',
    name: 'News Article',
    description: 'News article reading view',
    category: 'News',
    icon: Sparkles,
    components: [
      {
        type: 'image',
        props: {
          source: 'https://images.pexels.com/photos/1496192/pexels-photo-1496192.jpeg?auto=compress&cs=tinysrgb&w=600',
          borderRadius: 0,
          aspectRatio: '16:9',
          opacity: 1,
        },
        position_x: 0,
        position_y: 0,
        width: 375,
        height: 220,
      },
      {
        type: 'text',
        props: {
          text: 'Breaking News: Tech Innovation',
          fontSize: 24,
          color: '#000000',
          fontWeight: 'bold',
          lineHeight: 1.3,
        },
        position_x: 20,
        position_y: 240,
        width: 335,
        height: 64,
      },
      {
        type: 'text',
        props: {
          text: 'By John Doe • 5 min read',
          fontSize: 14,
          color: '#6B7280',
          fontWeight: 'normal',
        },
        position_x: 20,
        position_y: 315,
        width: 335,
        height: 20,
      },
      {
        type: 'container',
        props: {
          backgroundColor: '#F9FAFB',
          borderRadius: 12,
          padding: 16,
          borderWidth: 0,
        },
        position_x: 20,
        position_y: 350,
        width: 335,
        height: 150,
      },
    ],
  },
  {
    id: 'music-player',
    name: 'Music Player',
    description: 'Now playing music interface',
    category: 'Music',
    icon: Sparkles,
    components: [
      {
        type: 'container',
        props: {
          backgroundColor: '#1C1C1E',
          gradientColors: ['#6366F1', '#8B5CF6'],
          gradientDirection: 'vertical',
          borderRadius: 0,
          padding: 0,
          borderWidth: 0,
        },
        position_x: 0,
        position_y: 0,
        width: 375,
        height: 812,
      },
      {
        type: 'image',
        props: {
          source: 'https://images.pexels.com/photos/1763075/pexels-photo-1763075.jpeg?auto=compress&cs=tinysrgb&w=600',
          borderRadius: 24,
          aspectRatio: '1:1',
          opacity: 1,
          shadowColor: '#000000',
          shadowOpacity: 0.5,
          shadowRadius: 24,
        },
        position_x: 37,
        position_y: 100,
        width: 300,
        height: 300,
      },
      {
        type: 'text',
        props: {
          text: 'Summer Vibes',
          fontSize: 28,
          color: '#FFFFFF',
          fontWeight: 'bold',
          textAlign: 'center',
        },
        position_x: 37,
        position_y: 430,
        width: 300,
        height: 36,
      },
      {
        type: 'text',
        props: {
          text: 'The Weeknd',
          fontSize: 16,
          color: '#FFFFFF99',
          fontWeight: 'normal',
          textAlign: 'center',
        },
        position_x: 87,
        position_y: 475,
        width: 200,
        height: 24,
      },
    ],
  },
  {
    id: 'chat-messaging',
    name: 'Chat Interface',
    description: 'Messaging conversation view',
    category: 'Chat',
    icon: Sparkles,
    components: [
      {
        type: 'header',
        props: {
          title: 'Messages',
          backgroundColor: '#000000',
          textColor: '#FFFFFF',
          fontSize: 22,
          fontWeight: 'bold',
          showBackButton: true,
        },
        position_x: 0,
        position_y: 0,
        width: 375,
        height: 60,
      },
      {
        type: 'container',
        props: {
          backgroundColor: '#3B82F6',
          borderRadius: 16,
          padding: 12,
          borderWidth: 0,
        },
        position_x: 100,
        position_y: 80,
        width: 255,
        height: 70,
      },
      {
        type: 'text',
        props: {
          text: 'Hey! How are you?',
          fontSize: 15,
          color: '#FFFFFF',
          fontWeight: 'normal',
        },
        position_x: 115,
        position_y: 95,
        width: 225,
        height: 40,
      },
      {
        type: 'container',
        props: {
          backgroundColor: '#E5E7EB',
          borderRadius: 16,
          padding: 12,
          borderWidth: 0,
        },
        position_x: 20,
        position_y: 170,
        width: 255,
        height: 70,
      },
      {
        type: 'input',
        props: {
          placeholder: 'Type a message...',
          backgroundColor: '#F3F4F6',
          textColor: '#000000',
          borderColor: '#E5E7EB',
          borderWidth: 1,
          borderRadius: 24,
        },
        position_x: 20,
        position_y: 720,
        width: 335,
        height: 48,
      },
    ],
  },
  {
    id: 'calendar-event',
    name: 'Calendar Events',
    description: 'Event calendar view',
    category: 'Calendar',
    icon: Sparkles,
    components: [
      {
        type: 'header',
        props: {
          title: 'Calendar',
          backgroundColor: '#7C3AED',
          textColor: '#FFFFFF',
          fontSize: 22,
          fontWeight: 'bold',
          showBackButton: false,
        },
        position_x: 0,
        position_y: 0,
        width: 375,
        height: 60,
      },
      {
        type: 'text',
        props: {
          text: 'December 2024',
          fontSize: 24,
          color: '#000000',
          fontWeight: 'bold',
        },
        position_x: 20,
        position_y: 80,
        width: 335,
        height: 32,
      },
      {
        type: 'container',
        props: {
          backgroundColor: '#F5F3FF',
          borderRadius: 16,
          padding: 16,
          borderWidth: 1,
          borderColor: '#DDD6FE',
        },
        position_x: 20,
        position_y: 130,
        width: 335,
        height: 80,
      },
      {
        type: 'card',
        props: {
          title: 'Team Meeting',
          subtitle: '10:00 AM - 11:00 AM',
          backgroundColor: '#FFFFFF',
          borderRadius: 12,
          padding: 16,
          borderWidth: 1,
          borderColor: '#E5E7EB',
        },
        position_x: 20,
        position_y: 230,
        width: 335,
        height: 100,
      },
    ],
  },
  {
    id: 'analytics-dashboard',
    name: 'Analytics Dashboard',
    description: 'Statistics and metrics view',
    category: 'Analytics',
    icon: TrendingUp,
    components: [
      {
        type: 'header',
        props: {
          title: 'Analytics',
          backgroundColor: '#1F2937',
          textColor: '#FFFFFF',
          fontSize: 22,
          fontWeight: 'bold',
          showBackButton: false,
        },
        position_x: 0,
        position_y: 0,
        width: 375,
        height: 60,
      },
      {
        type: 'card',
        props: {
          title: '12.5K',
          subtitle: 'Total Users',
          backgroundColor: '#10B981',
          gradientColors: ['#10B981', '#059669'],
          gradientDirection: 'diagonal',
          borderRadius: 16,
          padding: 20,
        },
        position_x: 20,
        position_y: 80,
        width: 165,
        height: 120,
      },
      {
        type: 'card',
        props: {
          title: '8.2K',
          subtitle: 'Active Sessions',
          backgroundColor: '#3B82F6',
          gradientColors: ['#3B82F6', '#2563EB'],
          gradientDirection: 'diagonal',
          borderRadius: 16,
          padding: 20,
        },
        position_x: 190,
        position_y: 80,
        width: 165,
        height: 120,
      },
      {
        type: 'container',
        props: {
          backgroundColor: '#FFFFFF',
          borderRadius: 16,
          padding: 20,
          borderWidth: 1,
          borderColor: '#E5E7EB',
        },
        position_x: 20,
        position_y: 220,
        width: 335,
        height: 200,
      },
    ],
  },
  {
    id: 'weather-forecast',
    name: 'Weather App',
    description: 'Weather forecast display',
    category: 'Weather',
    icon: Sparkles,
    components: [
      {
        type: 'container',
        props: {
          backgroundColor: '#0EA5E9',
          gradientColors: ['#0EA5E9', '#0284C7', '#0369A1'],
          gradientDirection: 'vertical',
          borderRadius: 0,
          padding: 0,
          borderWidth: 0,
        },
        position_x: 0,
        position_y: 0,
        width: 375,
        height: 400,
      },
      {
        type: 'text',
        props: {
          text: 'San Francisco',
          fontSize: 32,
          color: '#FFFFFF',
          fontWeight: 'bold',
          textAlign: 'center',
        },
        position_x: 87,
        position_y: 80,
        width: 200,
        height: 40,
      },
      {
        type: 'text',
        props: {
          text: '72°',
          fontSize: 72,
          color: '#FFFFFF',
          fontWeight: 'bold',
          textAlign: 'center',
        },
        position_x: 137,
        position_y: 140,
        width: 100,
        height: 90,
      },
      {
        type: 'text',
        props: {
          text: 'Partly Cloudy',
          fontSize: 18,
          color: '#FFFFFF99',
          fontWeight: '500',
          textAlign: 'center',
        },
        position_x: 112,
        position_y: 240,
        width: 150,
        height: 26,
      },
      {
        type: 'container',
        props: {
          backgroundColor: '#FFFFFF',
          borderRadius: 24,
          padding: 20,
          borderWidth: 0,
        },
        position_x: 20,
        position_y: 320,
        width: 335,
        height: 200,
      },
    ],
  },
  {
    id: 'recipe-detail',
    name: 'Recipe Detail',
    description: 'Cooking recipe view',
    category: 'Food',
    icon: Utensils,
    components: [
      {
        type: 'image',
        props: {
          source: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600',
          borderRadius: 0,
          aspectRatio: '4:3',
          opacity: 1,
        },
        position_x: 0,
        position_y: 0,
        width: 375,
        height: 280,
      },
      {
        type: 'text',
        props: {
          text: 'Homemade Pasta',
          fontSize: 28,
          color: '#000000',
          fontWeight: 'bold',
        },
        position_x: 20,
        position_y: 300,
        width: 335,
        height: 36,
      },
      {
        type: 'container',
        props: {
          backgroundColor: '#FEF3C7',
          borderRadius: 12,
          padding: 12,
          borderWidth: 1,
          borderColor: '#FDE68A',
        },
        position_x: 20,
        position_y: 350,
        width: 105,
        height: 60,
      },
      {
        type: 'text',
        props: {
          text: '30 min',
          fontSize: 16,
          color: '#92400E',
          fontWeight: '600',
          textAlign: 'center',
        },
        position_x: 35,
        position_y: 370,
        width: 75,
        height: 22,
      },
    ],
  },
  {
    id: 'photography-gallery',
    name: 'Photo Gallery',
    description: 'Image gallery grid',
    category: 'Photography',
    icon: Sparkles,
    components: [
      {
        type: 'header',
        props: {
          title: 'Gallery',
          backgroundColor: '#000000',
          textColor: '#FFFFFF',
          fontSize: 24,
          fontWeight: 'bold',
          showBackButton: false,
        },
        position_x: 0,
        position_y: 0,
        width: 375,
        height: 60,
      },
      {
        type: 'image',
        props: {
          source: 'https://images.pexels.com/photos/1166209/pexels-photo-1166209.jpeg?auto=compress&cs=tinysrgb&w=400',
          borderRadius: 8,
          aspectRatio: '1:1',
          opacity: 1,
        },
        position_x: 10,
        position_y: 75,
        width: 115,
        height: 115,
      },
      {
        type: 'image',
        props: {
          source: 'https://images.pexels.com/photos/1624496/pexels-photo-1624496.jpeg?auto=compress&cs=tinysrgb&w=400',
          borderRadius: 8,
          aspectRatio: '1:1',
          opacity: 1,
        },
        position_x: 130,
        position_y: 75,
        width: 115,
        height: 115,
      },
      {
        type: 'image',
        props: {
          source: 'https://images.pexels.com/photos/1770809/pexels-photo-1770809.jpeg?auto=compress&cs=tinysrgb&w=400',
          borderRadius: 8,
          aspectRatio: '1:1',
          opacity: 1,
        },
        position_x: 250,
        position_y: 75,
        width: 115,
        height: 115,
      },
      {
        type: 'image',
        props: {
          source: 'https://images.pexels.com/photos/2156881/pexels-photo-2156881.jpeg?auto=compress&cs=tinysrgb&w=400',
          borderRadius: 8,
          aspectRatio: '1:1',
          opacity: 1,
        },
        position_x: 10,
        position_y: 195,
        width: 115,
        height: 115,
      },
    ],
  },
  {
    id: 'game-leaderboard',
    name: 'Game Leaderboard',
    description: 'Gaming leaderboard rankings',
    category: 'Gaming',
    icon: TrendingUp,
    components: [
      {
        type: 'container',
        props: {
          backgroundColor: '#1F2937',
          gradientColors: ['#7C3AED', '#5B21B6'],
          gradientDirection: 'vertical',
          borderRadius: 0,
          padding: 0,
          borderWidth: 0,
        },
        position_x: 0,
        position_y: 0,
        width: 375,
        height: 200,
      },
      {
        type: 'text',
        props: {
          text: 'Leaderboard',
          fontSize: 32,
          color: '#FFFFFF',
          fontWeight: 'bold',
          textAlign: 'center',
        },
        position_x: 87,
        position_y: 80,
        width: 200,
        height: 40,
      },
      {
        type: 'card',
        props: {
          title: '1. Player One',
          subtitle: '15,340 points',
          backgroundColor: '#FCD34D',
          borderRadius: 12,
          padding: 16,
          borderWidth: 0,
        },
        position_x: 20,
        position_y: 220,
        width: 335,
        height: 80,
      },
      {
        type: 'card',
        props: {
          title: '2. Player Two',
          subtitle: '12,890 points',
          backgroundColor: '#D1D5DB',
          borderRadius: 12,
          padding: 16,
          borderWidth: 0,
        },
        position_x: 20,
        position_y: 315,
        width: 335,
        height: 80,
      },
      {
        type: 'card',
        props: {
          title: '3. Player Three',
          subtitle: '11,250 points',
          backgroundColor: '#FCA5A5',
          borderRadius: 12,
          padding: 16,
          borderWidth: 0,
        },
        position_x: 20,
        position_y: 410,
        width: 335,
        height: 80,
      },
    ],
  },
  {
    id: 'ecommerce-product-detail',
    name: 'Product Detail',
    description: 'Detailed product view with reviews',
    category: 'E-Commerce',
    icon: ShoppingBag,
    components: [
      {
        type: 'image',
        props: {
          source: 'https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg?auto=compress&cs=tinysrgb&w=600',
          borderRadius: 0,
          aspectRatio: '4:3',
          opacity: 1,
        },
        position_x: 0,
        position_y: 0,
        width: 375,
        height: 280,
      },
      {
        type: 'text',
        props: {
          text: 'Wireless Headphones Pro',
          fontSize: 24,
          color: '#000000',
          fontWeight: 'bold',
        },
        position_x: 20,
        position_y: 300,
        width: 335,
        height: 32,
      },
      {
        type: 'text',
        props: {
          text: '$299.99',
          fontSize: 28,
          color: '#EF4444',
          fontWeight: 'bold',
        },
        position_x: 20,
        position_y: 345,
        width: 150,
        height: 36,
      },
      {
        type: 'container',
        props: {
          backgroundColor: '#F9FAFB',
          borderRadius: 12,
          padding: 16,
          borderWidth: 0,
        },
        position_x: 20,
        position_y: 400,
        width: 335,
        height: 100,
      },
      {
        type: 'button',
        props: {
          text: 'Add to Cart',
          backgroundColor: '#000000',
          textColor: '#FFFFFF',
          fontSize: 16,
          fontWeight: 'bold',
          borderRadius: 12,
        },
        position_x: 20,
        position_y: 520,
        width: 335,
        height: 56,
      },
    ],
  },
  {
    id: 'meditation-mindfulness',
    name: 'Meditation Timer',
    description: 'Mindfulness meditation app',
    category: 'Wellness',
    icon: Heart,
    components: [
      {
        type: 'container',
        props: {
          backgroundColor: '#6366F1',
          gradientColors: ['#8B5CF6', '#6366F1', '#3B82F6'],
          gradientDirection: 'vertical',
          borderRadius: 0,
          padding: 0,
          borderWidth: 0,
        },
        position_x: 0,
        position_y: 0,
        width: 375,
        height: 812,
      },
      {
        type: 'text',
        props: {
          text: 'Breathe',
          fontSize: 36,
          color: '#FFFFFF',
          fontWeight: 'bold',
          textAlign: 'center',
        },
        position_x: 112,
        position_y: 100,
        width: 150,
        height: 44,
      },
      {
        type: 'container',
        props: {
          backgroundColor: '#FFFFFF33',
          borderRadius: 999,
          padding: 0,
          borderWidth: 3,
          borderColor: '#FFFFFF',
        },
        position_x: 87,
        position_y: 250,
        width: 200,
        height: 200,
      },
      {
        type: 'text',
        props: {
          text: '5:00',
          fontSize: 48,
          color: '#FFFFFF',
          fontWeight: 'bold',
          textAlign: 'center',
        },
        position_x: 137,
        position_y: 325,
        width: 100,
        height: 56,
      },
      {
        type: 'button',
        props: {
          text: 'Start Session',
          backgroundColor: '#FFFFFF',
          textColor: '#6366F1',
          fontSize: 18,
          fontWeight: 'bold',
          borderRadius: 999,
        },
        position_x: 87,
        position_y: 600,
        width: 200,
        height: 56,
      },
    ],
  },
];

interface ScreenTemplatesProps {
  onApplyTemplate: (components: any[]) => void;
  onClose: () => void;
}

export function ScreenTemplatesNew({ onApplyTemplate, onClose }: ScreenTemplatesProps) {
  const [selectedCategory, setSelectedCategory] = useState<string>('All');

  const categories = ['All', ...Array.from(new Set(TEMPLATES.map(t => t.category)))];

  const filteredTemplates = selectedCategory === 'All'
    ? TEMPLATES
    : TEMPLATES.filter(t => t.category === selectedCategory);

  return (
    <div className="fixed inset-0 bg-black/90 backdrop-blur-sm z-50 flex flex-col">
      <div className="glass-card m-4 p-4 flex items-center justify-between border-b border-white/10">
        <div>
          <h2 className="text-xl font-bold">Screen Templates</h2>
          <p className="text-white/60 text-sm">{TEMPLATES.length} professional templates</p>
        </div>
        <button onClick={onClose} className="glass-button p-2">
          <X className="w-5 h-5" />
        </button>
      </div>

      <div className="flex gap-2 px-4 pb-4 overflow-x-auto scrollbar-hide">
        {categories.map(category => (
          <button
            key={category}
            onClick={() => setSelectedCategory(category)}
            className={`px-4 py-2 rounded-lg whitespace-nowrap transition-all ${
              selectedCategory === category
                ? 'bg-orange-500 text-white'
                : 'glass-button'
            }`}
          >
            {category}
          </button>
        ))}
      </div>

      <div className="flex-1 overflow-y-auto p-4 grid grid-cols-1 md:grid-cols-2 gap-4 scrollbar-hide">
        {filteredTemplates.map((template) => {
          const Icon = template.icon;
          return (
            <button
              key={template.id}
              onClick={() => {
                onApplyTemplate(template.components);
                onClose();
              }}
              className="glass-card p-4 text-left hover:bg-white/10 transition-all group"
            >
              <div className="flex items-start gap-3">
                <div className="bg-orange-500/20 p-3 rounded-xl group-hover:bg-orange-500/30 transition-colors">
                  <Icon className="w-6 h-6 text-orange-500" />
                </div>
                <div className="flex-1">
                  <h3 className="font-semibold mb-1">{template.name}</h3>
                  <p className="text-sm text-white/60 mb-2">{template.description}</p>
                  <div className="flex items-center gap-2">
                    <span className="text-xs bg-orange-500/20 text-orange-400 px-2 py-1 rounded">
                      {template.category}
                    </span>
                    <span className="text-xs text-white/40">
                      {template.components.length} components
                    </span>
                  </div>
                </div>
              </div>
            </button>
          );
        })}
      </div>
    </div>
  );
}
